#!/usr/bin/env python3
"""Generate deterministic website evidence; --check fails when the artifact drifts."""
import argparse
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def build():
    config = json.loads((ROOT / 'tools/site/evidence.json').read_text())
    assert re.fullmatch(r'[0-9a-f]{40}', config['implementation_revision'])
    evidence = dict(config)
    outputs = {}
    evidence['source_hashes'] = {}
    for kind in ('retrieval', 'generation'):
        path = config[kind]
        raw = (ROOT / path).read_bytes()
        outputs[ROOT / f'site/data/{kind}.json'] = raw.decode()
        evidence['source_hashes'][path] = hashlib.sha256(raw).hexdigest()
        report = json.loads(raw)
        if kind == 'retrieval':
            assert report['aggregate']['queries'] == len(report['queries'])
            evidence['retrieval_report'] = {
                key: report[key] for key in ('run_id', 'mode', 'aggregate', 'queries')
            }
            # The UI only needs the top returned file, not full result lists.
            for query in evidence['retrieval_report']['queries']:
                query['top_results'] = query.get('top_results', [])[:1]
        else:
            evidence['generation_report'] = {
                'run_id': report['run_id'], 'answer': report['answer']
            }
    go_mod = (ROOT / 'go.mod').read_text()
    evidence['go_version'] = re.search(r'^go (\S+)', go_mod, re.M)[1]
    evidence['source_hashes']['go.mod'] = hashlib.sha256(go_mod.encode()).hexdigest()
    outputs[ROOT / 'site/evidence.js'] = '// Generated by tools/site/build_evidence.py; do not edit.\n' + \
        'const SITE_EVIDENCE = ' + json.dumps(evidence, indent=2, ensure_ascii=True) + ';\n'
    return outputs


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    outputs = build()
    if args.check:
        if any(not path.exists() or path.read_text() != content for path, content in outputs.items()):
            raise SystemExit('Website evidence is stale. Run: python3 tools/site/build_evidence.py')
        print('Website evidence is current.')
    else:
        for path, content in outputs.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
        print('Generated site/evidence.js and source report snapshots in site/data/')
